apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: aws-usw2-dev-apps-01-manifests
  namespace: argocd
spec:
  destination:
    name: in-cluster
    namespace: argocd
  source:
    path: argocd/clusters/aws/usw2/dev/apps-01/manifests
    repoURL: "git@github.com:xxxxx"
    targetRevision: HEAD
    directory:
      recurse: true
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
