apiVersion: v1
kind: Namespace
metadata:
  name: opentelemetry-collector
---
apiVersion: opentelemetry.io/v1alpha1
kind: OpenTelemetryCollector
metadata:
  name: otel-collector
  namespace: opentelemetry-collector
spec:
  mode: deployment
  image: otel/opentelemetry-collector-contrib:0.43.0
  resources:
    limits:
      cpu: 200m
      memory: 512Mi
    requests:
      cpu: 100m
      memory: 256Mi
  ports:
    - name: monitoring
      protocol: TCP
      port: 8888
      targetPort: 8888
    - name: otlp-grpc
      protocol: TCP
      port: 4317
      targetPort: 4317
    - name: otlp-http
      protocol: TCP
      port: 4318
      targetPort: 4318
  config: |
    receivers:
      otlp:
        protocols:
          grpc:
          http:
    processors:
      k8sattributes:
      memory_limiter:
        check_interval: 1s
        limit_percentage: 70
        spike_limit_percentage: 20
    extensions:
      memory_ballast:
        size_in_percentage: 50    
    exporters:
      logging:
        loglevel: info
      jaeger:
        endpoint: "jaeger-collector.jaeger.svc.cluster.local:14250"
        tls:
          insecure: true
    service:
      pipelines:
        traces/1:
          receivers: [otlp]
          processors: [memory_limiter, k8sattributes]
          exporters: [jaeger, logging]
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: opentelemetry-collector
  namespace: opentelemetry-collector
spec:
  endpoints:
    - interval: 30s
      path: /metrics
      port: "monitoring"
  selector:
    matchLabels:
      app.kubernetes.io/component: opentelemetry-collector
      app.kubernetes.io/name: otel-collector-collector-monitoring
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: opentelemetry-collector-role
rules:
  - verbs:
      - get
      - list
      - watch
    apiGroups:
      - ''
    resources:
      - pods
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: opentelemetry-collector
subjects:
  - kind: ServiceAccount
    name: otel-collector-collector
    namespace: opentelemetry-collector
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: opentelemetry-collector-role
