apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: aws-usw2-dev-apps-01-aws-load-balancer-controller
spec:
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
  destination:
    name: aws-usw2-dev-apps-01
    namespace: kube-system
  source:
    repoURL: "https://aws.github.io/eks-charts"
    chart: aws-load-balancer-controller
    targetRevision: "1.4.2"
    helm:
      values: |
        replicaCount: 1
