apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: aws-usw2-dev-apps-01-cluster-autoscaler
spec:
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
  destination:
    name: aws-usw2-dev-apps-01
    namespace: kube-system
  source:
    repoURL: "https://kubernetes.github.io/autoscaler"
    chart: cluster-autoscaler
    targetRevision: "9.19.2"
    helm:
      values: |
        image:
          repository: k8s.gcr.io/autoscaling/cluster-autoscaler
          tag: v1.21.3
