apiVersion: velero.io/v1
kind: BackupStorageLocation
metadata:
  name: default
  namespace: velero
spec:
  backupSyncPeriod: 2m0s
  provider: aws
  objectStorage:
    bucket: xxxxx
  credential:
    name: aws-credentials
    key: aws
  config:
    region: us-west-2
    profile: "default"
